development:
  address: smtp.gmail.com
  port: 587
  authentication: plain
  user_name: bvrn007@gmail.com
  password: 4s3nAdmin!69
  enable_starttls_auto: true
production:
  address: mail.flyerzero.com
  port: 587
  authentication: login
  user_name: xxx
  password: yyy
